### ISSUE TITLE
Mvnrepository Version

### ISSUE THREAD

**Issue by Urm3l** [crealytics/spark-google-analytics#13]
Hi,
I wanted to use the most recent lib version for scala 2.10

Sadly these are not on mvnrepository.com

Can you add them or at least update the 2.11 to 1.1.0?

Thanks in advance

**Comment by nightscape** [comment]
Hi @Urm3l,

thanks for the reminder :smiley:
I just published 1.1.0 for both 2.11 and 2.10.
Can you give it a try and close this issue if it works?

**Comment by Urm3l** [comment]
Thank you so much!
