### ISSUE TITLE
Seems that the goal metrices are not correctly resolved

### ISSUE THREAD

**Issue by thomas-hoppe** [crealytics/spark-google-analytics#4]
org.apache.spark.sql.AnalysisException: cannot resolve 'goal1Starts' given input columns adsenseCoverage, dcmImpressions, buyToDetailRate, productRefundAmount, goalXXStarts, dcmFloodlightRevenue, productListViews, userTimingSample,

**Comment by thomas-hoppe** [comment]
Same wil probably hold for goal1Completions, goal1ConversionRate etc. as well

**Comment by nightscape** [comment]
Analytics has a concept of [templatized columns](https://developers.google.com/analytics/devguides/reporting/metadata/v3/devguide#templatized). We were not aware of this, but it should be handled correctly starting in version 0.8.3.
