### ISSUE TITLE
Parse custom and calculated metrics as decimal

### ISSUE THREAD

**Issue by SebastianEdwards** [crealytics/spark-google-analytics#8]
Contrary to the metadata description - the metric types ga:metricXX and ga:calcMetric_ both have variable data types. See [API docs](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=custom_variables_or_columns&jump=ga_metricxx).

This mismatch leads to errors like this (example is a TIME custom metric):

```scala
display(df.select(
  col("date"),
  col("pagePath"),
  col("metric1").alias("Total engaged time")
))

// NumberFormatException: For input string: "26.0"
```

I believe it would be safe to parse these columns as `DECIMAL` as it would handle all variants (`FLOAT`, `INTEGER`, `CURRENCY`, even `TIME` is returned in seconds. I'm not 100% sure how the `PERCENT` type is formatted but I imagine it is sans the percentage sign).

**Comment by nightscape** [comment]
Hey @SebastianEdwards, could you try the following:
Can you create example metrics for all different types and inspect in a debugging session (I use IntelliJ and start a Scala console in debug mode) what their format is?
When you set a breakpoint somewhere at [line 185 or later in `AnalyticsRelation`](https://github.com/crealytics/spark-google-analytics/blob/master/src/main/scala/com/crealytics/google/analytics/AnalyticsRelation.scala#L185)
`firstResult` should contain a `DataMap$Entry` called `rows` which contains the String representations of the data, you could check the `PERCENT` assumption there.
There's also a `columnHeaders` entry containing the column types of the result. It would be interesting to know if these columns show the actual type of the custom metric. If they do we might use those types for the actual parsing, although we'd still have to convert them into the format that Spark expects.

The `DECIMAL` option sounds good if we're sure that all of them can be cast to decimals.
Another option would be to introduce artificial columns like `metric1_time`, `metric1_currency`, ...
although I'm not even sure I like that solution myself :wink:

**Comment by SebastianEdwards** [comment]
Yep, `header.getDataType` does in fact contain the actual type for each column.

Here's how the number `13` is formatted under every variant:
```scala
"13" // INTEGER
"13.0" // FLOAT
"1.3E-5" // CURRENCY
"13.0" // TIME
"1300.0" // PERCENT
```

Not quite sure what to do with this now though as the schema is already defined by the time the headers are inspectable.

**Comment by SebastianEdwards** [comment]
While we're on the subject - I think `"TIME"` should be mapped to `"DECIMAL"` [here](https://github.com/crealytics/spark-google-analytics/blob/master/src/main/scala/com/crealytics/google/analytics/AnalyticsRelation.scala#L110). At the moment querying metrics like `timeOnPage` will result in a: 
```
IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
```

**Comment by SebastianEdwards** [comment]
Opened a PR for the two issues above. Took the approach of the simplest thing that works (DECIMAL parsing). Have tested against all variant types and seems to be working well.
